services:
  antibody-api:
    hostname: antibody-api
    container_name: antibody-api
    # Use the published image from DockerHub instead of local build
    # Exit with an error message containing err if ANTIBODY_API_VERSION is unset or empty in the environment
    image: hubmap/antibody-api:${ANTIBODY_API_VERSION:?err}
    environment:
      # UID and GID 1001 to match the hive user by default
      - HOST_GID=${HOST_GID:-1001}
      - HOST_UID=${HOST_UID:-1001}
    init: true
    restart: always
    networks:
      - gateway_hubmap
    volumes:
      # Flask configuration
      - ./instance:/app/var/antibodyapi-instance
      # uWSGI log
      - ./server/log:/app/server/log
      - ./VERSION:/app/server/VERSION
      - ./BUILD:/app/server/BUILD
    # Send docker logs to AWS CloudWatch
    logging: 
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: antibody-api-docker-logs
        awslogs-stream: ${LOG_STREAM}

networks:
  gateway_hubmap:
    external: true
